//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiMvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eData
    {
        public int dataId { get; set; }
        public System.DateTime dataDateTime { get; set; }
        public string data { get; set; }
    }
}
