//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiMvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eDelivery
    {
        public int deliveryId { get; set; }
        public System.DateTime orderDate { get; set; }
        public int orderedPc { get; set; }
        public int deliveredPc { get; set; }
        public Nullable<int> notdeliveredPc { get; set; }
        public int countryId { get; set; }
        public Nullable<int> notdeliveredRel { get; set; }
    
        public virtual eCountry eCountry { get; set; }
    }
}
