//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiMvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eDiagramdata
    {
        public int DiagramdataId { get; set; }
        public string DiagramdataLabel { get; set; }
        public string Diagramdata { get; set; }
    }
}
