//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiMvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eKvp
    {
        public int kvpId { get; set; }
        public string kvpName { get; set; }
        public System.DateTime kvpDate { get; set; }
        public int kvpClassId { get; set; }
        public int kvpStateId { get; set; }
    
        public virtual eKvpClass eKvpClass { get; set; }
        public virtual eKvpState eKvpState { get; set; }
    }
}
