//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiMvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ePcbDaily
    {
        public int pcbDailyId { get; set; }
        public System.DateTime productionDay { get; set; }
        public int pcbQuantity { get; set; }
        public decimal pcbSumPrice { get; set; }
        public int pcbGenerationId { get; set; }
        public int pcbClassId { get; set; }
    
        public virtual ePcbClass ePcbClass { get; set; }
        public virtual ePcbGeneration ePcbGeneration { get; set; }
    }
}
